server:
  port: ${APP_PORT:8090}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  max-http-request-header-size: 40KB
  shutdown: ${SHUTDOWN:graceful}
  error:
    whitelabel:
      enabled: false

spring:
  lifecycle:
    timeout-per-shutdown-phase: ${TIMEOUT_PER_SHUTDOWN_PHASE:10s}
  application:
    name: hw06_payment_service
  servlet:
    multipart:
      max-file-size: ${MULTIPART_FILE_MAX:10MB}
      max-request-size: ${MULTIPART_REQUEST_MAX:10MB}
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        types:
          print:
            banner: false
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: ${SHOW_SQL:true}
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:none}
    open-in-view: false
  web:
    resources:
      add-mappings: false
  flyway:
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:true}
    fail-on-missing-locations: ${FLYWAY_FAIL_ON_MISSING_LOCATIONS:true}
    locations: ${FLYWAY_LOCATIONS:classpath:db/migration}
    enabled: true

logging:
  level:
    ROOT: ${LOGGING_LEVEL_ROOT:info}
    org.example: ${LOGGING_LEVEL:debug}

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:true}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}
    url: /product-service-rest-v1.yaml # Документацию для Сваггера генерируем на основе спецификации
